---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-arc-runners
  description: github-arc-runners
  annotations:
    github.com/project-slug: CloudNomster/helm-gh-arc-runners
    argocd/app-name: helm-gh-arc-runners
  links:
    - url: https://github.com/CloudNomster/helm-gh-arc-runners
      title: Github Actions Runners helm repository
      icon: github
      type: Code
    - url: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller
      title: Actions Runner Controller
      icon: docs
      type: docs
  tags:
    - github
    - arc

spec:
  type: code
  owner: group:team-nomster
  lifecycle: testing
